package me.ohvalsgod.overwatch.jedis.handler;

public enum OverwatchPayload {

    OVERWATCH_PAYLOAD_GAME_END,
    OVERWATCH_PAYLOAD_GAME_START,
    OVERWATCH_PAYLOAD_GAME_LOOKING_FOR_PLAYERS,
    OVERWATCH_PAYLOAD_GAME_END_PLAYER_LEFT,
    OVERWATCH_PAYLOAD_GAME_END_PLAYER_JOINED;

}
